### PR TITLE
Create telnet via rs2ttl  SMEG i HW 5.xx

### PR DESCRIPTION
**Pull request by P208PUG**
telnetsmeg5xx

### CODE REVIEW

**Comment by bousqi** [comment]
Interesting view of hardware. I recommend to udpate README.md,  insert this URL / Image in a proper way before I pull.

**Comment by P208PUG** [comment]
im new on github and don't know howto do this

**Comment by bousqi** [comment]
I'll try to add a hardware dedicated section with this picture. Do you have other picture for extracting SMEG unit from car itself ?

**Comment by vidarrt9** [comment]
@P208PUG have you been able to get the SMEG+ unit to start outside a car? I just tried that for the first time giving it 14V as per the PDF that is circulating (+14V on pin 12 and GND on pin 16 of part A of the MOST socket on the back).

Now it's indeed drawing some power, then seemingly switching off again, then drawing power again as I can see on my power supply.

Any ideas?

**Comment by P208PUG** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I made a bench simulator from old BSI to have posiblilty connect with diagnostic socket...                                                                                                                                                                                                                                                                                                                         Od: notifications@github.comWysłano: 4 września 2020 00:20Do: SMEG_PLUS@noreply.github.comOdp. do: reply@reply.github.comDW: marcin@bbmail.pl; mention@noreply.github.comTemat: Re: [bousqi/SMEG_PLUS] Create telnet via rs2ttl  SMEG i HW 5.xx (#2)  
@P208PUG have you been able to get the SMEG+ unit to start outside a car? I just tried that for the first time giving it 14V as per the PDF that is circulating (+12V on pin 12 and GND on pin 16 of part A of the MOST socket on the back).
Now it's indeed drawing some power, then seemingly switching off again, then drawing power again as I can see on my power supply.
Any ideas?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vidarrt9** [comment]
@P208PUG sorry, I think that was an empty response.

Either way, I now know that I _also_ need to connect HS and LS CAN in addition to power.

**Comment by bousqi** [comment]
@P208PUG  @vidarrt9 
do you mind sharing some pictures of the bench setup / units / or any view of the hardware ?

**Comment by vidarrt9** [comment]
> @P208PUG @vidarrt9
> do you mind sharing some pictures of the bench setup / units / or any view of the hardware ?

In particular of the hardware, yes I have taken a number of photos and am preparing those to be added in a GitHub Wiki. Currently I am keeping the project with private visibility as I need to prepare some stuff. Basically right now it's rather raw (I only refer to some other modules via submodules). So I want to put some things in order, collect whatever I have so far found and put this all into one Wiki. Since the Wikis are also Git repos this is kind of convenient.

I could already provide photos of the UART adapter and the soldered contacts as well as the PSU, but that's sort of pointless before I _actually_ get it to work. Which requires some CAN magic, I assume.

**Comment by P208PUG** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Found something better :) https://www.forum-peugeot.com/Forum/threads/tuto-t%C3%A9l%C3%A9codage-et-calibration-dun-nac-rcc-cirocco-sans-diagbox-via-arduino.121767/                                                                                                                                                                                                                                                                                                                        From: notifications@github.comSent: 4 September 2020 18:15To: SMEG_PLUS@noreply.github.comReply to: reply@reply.github.comCc: marcin@bbmail.pl; mention@noreply.github.comSubject: Re: [bousqi/SMEG_PLUS] Create telnet via rs2ttl  SMEG i HW 5.xx (#2)  
@P208PUG  @vidarrt9
do you mind sharing some pictures of the bench setup / units / or any view of the hardware ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
